name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - env:
        SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES }}
      run: echo "$SECRETS_PROPERTIES" | base64 -d > ./secrets.properties
    - uses: actions/checkout@v2
    - name: Android Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
    - name: Build Apk
      uses: yuanjinsongquyi/action_android_build@v1
      with:
        APP_NAME: Spoonacular_DAM
        GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}  
